apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyBudget

spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyBudget
  template:
    metadata:
      labels:
        app: MyBudget

    spec:
      containers:
        - name: MyBudget-container
          image: jp.icr.io/expense-tracker/expense-tracker
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP